### ISSUE TITLE
NameError: global name 'NotFound' is not defined

### ISSUE THREAD

**Issue by RafaelFarias** [collective/collective.googleanalytics#29]
I am experiencing this error in the master branch . It occurs at instance startup .

```
2016-07-28 14:34:09 ERROR plone.app.viewletmanager rendering of plone.htmlhead.links in collective.googleanalytics.tracking fails: global name 'NotFound' is not defined

 - Expression: "view/renderPageview"
 - Filename:   ... y2.7.egg/collective/googleanalytics/viewlets/tracking.pt
 - Location:   (line 19: col 62)
 - Source:     ... tal:content="structure view/renderPageview">
                                            ^^^^^^^^^^^^^^^^^^^
```

(more details in [error_log.txt](https://github.com/collective/collective.googleanalytics/files/390542/error_log.txt) atached)

I realized that the ' NotFound ' was added in this commit: https://github.com/collective/collective.googleanalytics/commit/08f6b84e236515d07e9195a8f209e14abe0e08cb

**Comment by b0n** [comment]
I saw same error too.

```
2016-11-08 16:45:03 ERROR plone.app.viewletmanager rendering of plone.htmlhead.links in collective.googleanalytics.tracking fails: global name 'NotFound' is not defined
Traceback (most recent call last):
  File "/usr/local/Plone/buildout-cache/eggs/plone.app.viewletmanager-2.0.5-py2.7.egg/plone/app/viewletmanager/manager.py", line 105, in render
    html.append(viewlet.render())
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/usr/local/Plone/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/usr/local/Plone/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 240, in __call__
    interpreter()
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 742, in do_insertStructure_tal
    structure = self.engine.evaluateStructure(expr)
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 218, in evaluateStructure
    text = super(ZopeContext, self).evaluateStructure(expr)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/usr/local/Plone/buildout-cache/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 155, in _eval
    return render(ob, econtext.vars)
  File "/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 117, in render
    ob = ob()
  File "/usr/local/Plone/buildout-cache/eggs/collective.googleanalytics-1.5.0-py2.7.egg/collective/googleanalytics/viewlets/tracking.py", line 74, in renderPageview
    if exc_info == NotFound:
NameError: global name 'NotFound' is not defined
```

**Comment by tomgross** [comment]
The error handling has been restructured: https://github.com/collective/collective.googleanalytics/commit/f5e5e9bc743e5e6273f007f8e98b3a562592c192
