### ISSUE TITLE
"File downloads" and "E-mail links" plugins are broken

### ISSUE THREAD

**Issue by laulaz** [collective/collective.googleanalytics#33]
All other plugins do not generate any traceback.

When I select "File downloads" plugin, I get this traceback :
```
Traceback (most recent call last):
  File "/Users/laurent/.buildout/eggs/plone.app.viewletmanager-2.0.6-py2.7.egg/plone/app/viewletmanager/manager.py", line 105, in render
    html.append(viewlet.render())
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/Users/laurent/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/Users/laurent/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 240, in __call__
    interpreter()
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 742, in do_insertStructure_tal
    structure = self.engine.evaluateStructure(expr)
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 218, in evaluateStructure
    text = super(ZopeContext, self).evaluateStructure(expr)
  File "/Users/laurent/.buildout/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/Users/laurent/.buildout/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 155, in _eval
    return render(ob, econtext.vars)
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 117, in render
    ob = ob()
  File "/Users/laurent/.buildout/eggs/collective.googleanalytics-1.6.1-py2.7.egg/collective/googleanalytics/viewlets/tracking.py", line 63, in renderPlugins
    results.append(plugin())
  File "/Users/laurent/.buildout/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/viewpagetemplatefile.py", line 83, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/Users/laurent/.buildout/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/viewpagetemplatefile.py", line 51, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/Users/laurent/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 126, in pt_render
    raise PTRuntimeError(str(self._v_errors))
PTRuntimeError: ['Compilation failed', 'zope.tal.taldefs.TALError: $ must be doubled or followed by a simple path in expression u"string:\\n    /*<![CDATA[*/\\n    jQuery(function($) {\\n        var extensions = ${view/file_extensions};\\n        var extensionsPattern = new RegExp(\'\\\\\\\\.((\' + extensions.join(\')|(\') + \'))$\', \'g\');\\n        $(\'a\').filter(function () {\\n            return this.href.match(extensionsPattern) || this.href.match(/\\\\/at_download\\\\//g);\\n        }).click(function () {\\n            _gaq.push([\'_trackEvent\', \'File\', \'Download\', $(this).attr(\'href\')]);\\n        });\\n    });\\n    /*]]>*/\\n", at line 1, column 1']
```

When I select "E-mail links" plugin, I get this traceback :
```
Traceback (most recent call last):
  File "/Users/laurent/.buildout/eggs/plone.app.viewletmanager-2.0.6-py2.7.egg/plone/app/viewletmanager/manager.py", line 105, in render
    html.append(viewlet.render())
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/Users/laurent/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/Users/laurent/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 240, in __call__
    interpreter()
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 271, in __call__
    self.interpret(self.program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 852, in do_condition
    self.interpret(block)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 533, in do_optTag_tal
    self.do_optTag(stuff)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 518, in do_optTag
    return self.no_tag(start, program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 513, in no_tag
    self.interpret(program)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 343, in interpret
    handlers[opcode](self, args)
  File "/Users/laurent/.buildout/eggs/zope.tal-3.5.2-py2.7.egg/zope/tal/talinterpreter.py", line 742, in do_insertStructure_tal
    structure = self.engine.evaluateStructure(expr)
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 218, in evaluateStructure
    text = super(ZopeContext, self).evaluateStructure(expr)
  File "/Users/laurent/.buildout/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/tales.py", line 696, in evaluate
    return expression(self)
  File "/Users/laurent/.buildout/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py", line 217, in __call__
    return self._eval(econtext)
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 155, in _eval
    return render(ob, econtext.vars)
  File "/Users/laurent/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Products/PageTemplates/Expressions.py", line 117, in render
    ob = ob()
  File "/Users/laurent/.buildout/eggs/collective.googleanalytics-1.6.1-py2.7.egg/collective/googleanalytics/viewlets/tracking.py", line 63, in renderPlugins
    results.append(plugin())
  File "/Users/laurent/.buildout/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/viewpagetemplatefile.py", line 83, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/Users/laurent/.buildout/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/viewpagetemplatefile.py", line 51, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/Users/laurent/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 126, in pt_render
    raise PTRuntimeError(str(self._v_errors))
PTRuntimeError: ['Compilation failed', 'zope.tal.taldefs.TALError: $ must be doubled or followed by a simple path in expression u\'string:\\n    /*<![CDATA[*/\\n    jQuery(function($) {\\n        $(\\\'a[href^="mailto"]\\\').click(function () {\\n            var email = $(this).attr(\\\'href\\\').replace(\\\'mailto:\\\', \\\'\\\');\\n            _gaq.push([\\\'_trackEvent\\\', \\\'External\\\', \\\'E-mail\\\', email]);\\n        });\\n    });\\n    /*]]>*/\\n\', at line 1, column 1']
```

**Comment by mikejmets** [comment]
I have the same issue on 5.2.2 (py 2):

```
2021-02-05 10:56:56,542 ERROR   [plone.app.viewletmanager:118][waitress-0] Error while rendering viewlet-manager=plone.htmlhead.links, viewlet=collective.googleanalytics.tracking
Traceback (most recent call last):
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/plone.app.viewletmanager-3.1.1-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 126, in __call__
    return self.__func__(__self__, *args, **kw)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 61, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/zope.pagetemplate-4.5.0-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 135, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Products/PageTemplates/engine.py", line 367, in __call__
    return template.render(**kwargs)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/z3c.pt-3.3.0-py2.7.egg/z3c/pt/pagetemplate.py", line 176, in render
    return base_renderer(**context)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Chameleon-3.8.1-py2.7.egg/chameleon/zpt/template.py", line 307, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Chameleon-3.8.1-py2.7.egg/chameleon/template.py", line 192, in render
    self._render(stream, econtext, rcontext)
  File "/home/mike/instances/8300-plone522/zeocluster/var/cache/ec7137931c40c1062626323c35659e70.py", line 185, in render
    __cache_140432097132496 = _static_140432354973456('path', u'view/renderPlugins', econtext=econtext)(_static_140432355030352(econtext, __zt_tmp))
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/zope.tales-5.1-py2.7.egg/zope/tales/expressions.py", line 250, in __call__
    return self._eval(econtext)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Products/PageTemplates/Expressions.py", line 196, in _eval
    return render(ob, econtext.vars)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Products/PageTemplates/Expressions.py", line 126, in render
    ob = ob()
  File "/home/mike/instances/8300-plone522/zeocluster/src/collective.googleanalytics/src/collective/googleanalytics/viewlets/tracking.py", line 60, in renderPlugins
    results.append(plugin())
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/zope.browserpage-4.4.0-py2.7.egg/zope/browserpage/viewpagetemplatefile.py", line 81, in __call__
    return self.__func__(im_self, *args, **kw)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/zope.browserpage-4.4.0-py2.7.egg/zope/browserpage/viewpagetemplatefile.py", line 49, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/zope.pagetemplate-4.5.0-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 135, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Zope-4.5.1-py2.7.egg/Products/PageTemplates/engine.py", line 367, in __call__
    return template.render(**kwargs)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/z3c.pt-3.3.0-py2.7.egg/z3c/pt/pagetemplate.py", line 176, in render
    return base_renderer(**context)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Chameleon-3.8.1-py2.7.egg/chameleon/zpt/template.py", line 307, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Chameleon-3.8.1-py2.7.egg/chameleon/template.py", line 214, in render
    raise_with_traceback(exc, tb)
  File "/home/mike/instances/8300-plone522/buildout-cache/eggs/Chameleon-3.8.1-py2.7.egg/chameleon/template.py", line 192, in render
    self._render(stream, econtext, rcontext)
  File "/home/mike/instances/8300-plone522/zeocluster/var/cache/bf4a969258acf8d7a8daa886e04f6b72.py", line 105, in render
    raise __exc
ExpressionError: $ must be doubled or followed by a simple path

 - String:     "
    /*<![CDATA[*/
    jQuery(function($) {
        var extensions = ${view/file_extensions};
        var extensionsPattern = new RegExp('\\.((' + extensions.join(')|(') + '))$', 'g');
        $('body').delegate('a', 'click', function() {
            if ($(this).attr('href').match(extensionsPattern) ||  $(this).attr('href').match(/\/at_download\//g)) {
                _gaq.push(['_trackEvent', 'File', 'Download', $(this).attr('href')]);
            }
        });
    });
    /*]]>*/
"
 - Filename:   /home/mike/instances/8300-plone522/zeocluster/src/collective.googleanalytics/src/collective/googleanalytics/tracking/download.pt
 - Location:   (line 1: col 61)
 - Source:     ... 
                   ^

 - Expression: "
    /*&lt;![CDATA[*/
    jQuery(function($) {
        var extensions = ${view/file_extensions};
        var extensionsPattern = new RegExp('\\.((' + extensions.join(')|(') + '))$', 'g');
        $('body').delegate('a', 'click', function() {
            if ($(this).attr('href').match(extensionsPattern) ||  $(this).attr('href').match(/\/at_download\//g)) {
                _gaq.push(['_trackEvent', 'File', 'Download', $(this).attr('href')]);
            }
        });
    });
    /*]]&"
 - Filename:   ... tics/src/collective/googleanalytics/tracking/download.pt
 - Location:   (line 1: col 61)
 - Source:     ... 
                   ^
 - Expression: "view/renderPlugins"
 - Filename:   ... tics/src/collective/googleanalytics/viewlets/tracking.pt
 - Location:   (line 17: col 38)
 - Source:     ... lock content="structure view/renderPlugins"></tal:block>
                                           ^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7f4d9ff34c30>
               context: <Document at /muizenbees/front-page>
               views: <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x7f4da7e547d0>
               modules: <zope.pagetemplate.engine.TraversableModuleImporter object at 0x7f4db3920910>
               args: ()
               nothing: None
               target_language: None
               default: <DEFAULT>
               request: <WSGIRequest, URL=https://muizenbees.co.za/front-page/document_view>
               loop: {}
               template: <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x7f4da454f190>
               translate: <function translate at 0x7f4da7e65650>
               options: {}
               view: <collective.googleanalytics.tracking.plugins.AnalyticsDownloadPlugin object at 0x7f4dacae2b10>
/home/mike/instances/8300-plone522/buildout-cache/eggs/zope.deprecation-4.4.0-py2.7.egg/zope/deprecation/deprecation.py:88: DeprecationWarning: isDefaultPage is deprecated. Import from Products.CMFPlone.defaultpage instead
  name)
```
I think this a general TALES error that is thown for a variety of reasons.
